### PR TITLE
Update US.md

### PR DESCRIPTION
**Pull request by brendonbultman**
added affirm

### CODE REVIEW

**Comment by GaganBhat** [comment]
It appears it's no longer open. @brendonbultman 

Also, the jobs site is - https://boards.greenhouse.io/affirm

This one seems to be one of those websites that take your email and continually send notifications.

**Comment by brendonbultman** [comment]
> It appears it's no longer open. @brendonbultman
> 
> Also, the jobs site is - https://boards.greenhouse.io/affirm
> 
> This one seems to be one of those websites that take your email and continually send notifications.

Wow, I applied earlier today and it's already closed. Sorry about that.

**Comment by GaganBhat** [comment]
Yeah, quite unfortunate. Seems like you got in just a few hours before it was closed. Good luck!

**Comment by BaruYogesh** [comment]
thanks for sharing, at least its nice to know that there will prob be a new post soon.

**Pull request closed without merging**
